### ISSUE TITLE
Add description for help command

### ISSUE THREAD

**Issue by YogPanjarale** [Clinify-Open-Sauce/SleepBot#1]
![image](https://user-images.githubusercontent.com/64301340/119515229-4f1bdb80-bd93-11eb-8ac7-aebfcbe01117.png)

Add Description  for the commands

**Comment by ZeusAbhijeet** [comment]
Easy Fix
Write the description on top of file as comments
![Example for fix](https://res.cloudinary.com/zeusabhijeet/image/upload/v1621953431/Github%20Stuff/SleepBot/Issue%201/Screenshot_2021-05-25_200501_eenedq.png)
