### ISSUE TITLE
Send a message when a focused person is pinged

### ISSUE THREAD

**Issue by YogPanjarale** [Clinify-Open-Sauce/SleepBot#4]
Send a message when a focused person is pinged , similar to afk

but it should allow to send message to #study-together

**Comment by ZeusAbhijeet** [comment]
Go ahead with pull request and link it to this issue

**Comment by YogPanjarale** [comment]
things to-do
 
- make a cogs listener to listen to messages,
- see the mentions for users in the message
- check if the user has `@Studying/Working` `<@&816873155246817290>` role 
- if so send message that {username} is Studying

**Comment by YogPanjarale** [comment]
Still Todo :(

**Comment by YogPanjarale** [comment]
working on it in [study-buddy-ping](https://github.com/Clinify-Open-Sauce/SleepBot/tree/study-buddy-ping)
